version: "3.8"
services:
  builder:
    profiles:
      - cli
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: bash
    volumes:
      - ./:/app-root
    environment:
      DATABASE_URL: "postgres://user:admin@db:5432/inzerator"
    depends_on:
      db:
        condition: service_healthy
  runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./:/app-root
    environment:
      DATABASE_URL: "postgres://user:admin@db:5432/inzerator"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 3s
      timeout: 60s
      retries: 30
      start_period: 5s
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
volumes:
  local_pgdata:
  pgadmin-data: